### ISSUE TITLE
"New Message" button in web plugin

### ISSUE THREAD

**Issue by devashishmamgain** [AppLozic/mobi-com-kit#51]
Add a "New Message" button in bottom of the web plugin, on click of it show the option to send message.

**Comment by devashishmamgain** [comment]
@aashishrawat  few issues in the code which you sent in mail, if the user is in the individual conversation screen then on press of "New Message", it should go back to the first main screen and show the message sending form at the bottom. Also, the js code need to move in mck-sidebox-1.0.js

**Comment by aashishrawat** [comment]
Hi

Whenever  click on this new message button but its not showing side box.

On Wed, Jul 1, 2015 at 5:43 PM, Devashish Datt Mamgain <
notifications@github.com> wrote:

> @aashishrawat <https://github.com/aashishrawat> few issues in the code
> which you sent in mail, if the user is in the individual conversation
> screen then on press of "New Message", it should go back to the first main
> screen and show the message sending form at the bottom. Also, the js code
> need to move in mck-sidebox-1.0.js
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/MobiComKit/mobi-com-kit/issues/51#issuecomment-117637029>
> .
>



-- 
Thanks & Regards
Ashish Rawat
